### ISSUE TITLE
More explicit error codes and messages

### ISSUE THREAD

**Issue by rickycpadilla** [passageidentity/passage-flutter#14]
### ⚠️ Problem
The Flutter SDK throws errors with relatively generic error codes, and the messages don't always match across iOS, Android, and web, so it can be hard to handle very specific issues.
<br>

### 🪄 Solution
The Passage Flutter SDK should throw more explicit errors, and they should match (as much as possible) across all three platforms so developers:
  * know exactly what kind of errors they might expect and
  * handle them gracefully with ease
 
See this Android error class as an example: https://github.com/passageidentity/passage-android/blob/main/passage/src/main/java/id/passage/android/exceptions/RegisterWithPasskeyException.kt
<br>

### 🤔 Challenges
The iOS (and web?) SDKs don't throw as granular of errors yet, so changes would need to be made to those before the Flutter SDK could make improvements.

**Comment by chimon2000** [comment]
@rickycpadilla I have some bandwidth to look at this issue.  It looks like codes coming back on web are granular.
