### ISSUE TITLE
Add namespace in build.gradle file

### ISSUE THREAD

**Issue by plchekspend** [passageidentity/passage-flutter#54]
@SinaSeylani @rickycpadilla @flanagankp 
After updating flutter sdk and android gradle plugin to 8.0+ now inside build.gradle file android bloc need to add namespace variable 
this is error:
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@2bd00ddf of type BuildFlowService.Parameters
   > A problem occurred configuring project ':passage_flutter'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See [https://developer.android.com/build/configure-app-module#set-namespace](https://d.android.com/r/tools/upgrade-assistant/set-namespace) for information about setting the namespace.
If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to [https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant](https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant )for general information about using the AGP Upgrade Assistant.

Please do this changes as soon as possible and release the new package version

**Comment by plchekspend** [comment]
any update @SinaSeylani  @rickycpadilla  @flanagankp ?

**Comment by SinaSeylani** [comment]
Hi @plchekspend , thanks for bringing this issue to our attention. I'm checking it out now.

**Comment by SinaSeylani** [comment]
The issue has been fixed. The new version (0.8.1) is now available.

**Comment by SinaSeylani** [comment]
@plchekspend, please don’t hesitate to contact us if you need further assistance
