### ISSUE TITLE
Not able to run or build the flutter app

### ISSUE THREAD

**Issue by plchekspend** [passageidentity/passage-flutter#59]
@SinaSeylani @flanagankp @rickycpadilla 
Right after updating passage_flutter plugin to latest i'm not able to run the app. 
here is the errors: 
```
/Volumes/Data/Flutter_Project/Chek-Flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:54: error: cannot find symbol
      flutterEngine.getPlugins().add(new id.passage.passage_flutter.PassageFlutterPlugin());
                                                                   ^
  symbol:   class PassageFlutterPlugin
  location: package id.passage.passage_flutter
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
Please have a look provide some solution. Thanks

**Comment by plchekspend** [comment]
any update @SinaSeylani @flanagankp ?

**Comment by plchekspend** [comment]
@SinaSeylani  I'm using flutter SDK 3.22.3 and latest android studio version Koala, let me know if you need any more information regarding error.

**Comment by SinaSeylani** [comment]
Hi @plchekspend , thanks for bringing this issue to our attention. I'm checking it out now.

**Comment by SinaSeylani** [comment]
Could you try to clean your project and check if you still have the same issue by following the steps below:

**Clean the Project:**

First, clean your project by running `flutter clean`.
Then, rebuild the project by running `flutter pub get` and `flutter build apk`.

**Rebuild the Android Project:**

If the problem continues, try invalidating caches and restarting Android Studio. Then, rebuild the Android project by running `./gradlew clean` and `./gradlew build`.

**Update Flutter:**
Ensure that your Flutter SDK is up to date (3.24.0). Some plugins require the latest version of Flutter to work correctly.

**Comment by plchekspend** [comment]
Sure @SinaSeylani  i'll try to clean the project check again and let you know the outcome, Thanks for quick response and solutions.
